### ISSUE TITLE
Resolving tenants on subdomain

### ISSUE THREAD

**Issue by KoenRijpstra** [leemason/tenantable#6]
It would be nice if there is an option to resolve tenants on subdomain only. Setting the main domain somewhere in the config and only set the subdomain in the database. This would be great for setting up multiple environments.

**Comment by leemason** [comment]
There isn't really a need for this as the package doesn't assume how you will use it, or register tenants.

The act of saving the tenants is down to your app so you can control what domains can be registered and what cant.

Using subdomains is the same as using full domains, you just save {subdomain}.domain.com to the db and don't allow {subdomain}.anotherdomain.com to be saved through validation.

That being said if you want to make a pull request which doesn't effect the current functionality but adds this feature its more than welcome.
